#!/bin/sh

#initialise Vbuddy
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# cleanup
rm -rf obj_dir
rm -f f1light.vcd

# run Verliator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1light.sv --exe f1light_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1light.mk Vf1light

# run executable simulation 
obj_dir/Vf1light